In [1]:
#

In [2]:
import numpy
import pandas

In [3]:
from mpydge.wrap.data import DataHandler

In [4]:
# Data

In [5]:
N = 10_000
dataframe = pandas.DataFrame(data={'A': numpy.array(numpy.arange(N)), 
                              'B': numpy.array(numpy.arange(N)) + numpy.random.normal(size=(N,)), 
                              'C': numpy.random.normal(size=(N,))})
dataframe

A             B         C
0        0     -0.826884 -0.697534
1        1     -0.231263  0.274161
2        2      1.680309  0.899829
3        3      3.462520 -1.640549
4        4      3.648093  0.374377
...    ...           ...       ...
9995  9995   9994.778958 -0.194535
9996  9996   9995.211056 -0.280797
9997  9997   9997.637095 -0.965938
9998  9998  10000.018676 -1.422004
9999  9999   9999.719083  2.682565

[10000 rows x 3 columns]

In [6]:
target = 'A'
quantitative = ['B', 'C']
qualitative = []

In [7]:
data = DataHandler(data_frame=dataframe, target=target, quantitative=quantitative, qualitative=qualitative)
data

In [8]:
data.values

(array([[-8.26883979e-01, -6.97533981e-01],
        [-2.31262858e-01,  2.74161331e-01],
        [ 1.68030898e+00,  8.99829233e-01],
        ...,
        [ 9.99763710e+03, -9.65937614e-01],
        [ 1.00000187e+04, -1.42200411e+00],
        [ 9.99971908e+03,  2.68256477e+00]]),
 array([[   0],
        [   1],
        [   2],
        ...,
        [9997],
        [9998],
        [9999]]))

In [9]:
data.names

(array(['B', 'C'], dtype=object), array(['A'], dtype='<U1'))

In [14]:
class DeadProcessor:
    
    def __init__(self):
        pass
    def fit(self, data):
        pass
    def transform(self, data):
        return data
    def inverse_transform(self, data):
        return data

In [10]:
# Model [OLS]

In [12]:
from mpydge.wrap.models.regression import OLR

In [15]:
model = OLR(data, preprocessor=DeadProcessor)
model

In [16]:
model.fit()

In [ ]:
model.correlation_matrix()

In [17]:
model.predict()

array([-8.21300689e-01, -2.33456240e-01,  1.67310525e+00, ...,
        9.99762515e+03,  1.00000104e+04,  9.99967793e+03])

In [18]:
model.score(measure='mae')

0.786193656372889

In [19]:
model.score(measure='r2')

0.9999998827844762

In [20]:
model.score(measure='r2_adj')

0.999999882761026

In [ ]:
model.melt_significance()

In [ ]:
model.data.values

In [ ]:
data = DataHandler(data_frame=dataframe, target=target, quantitative=quantitative, qualitative=qualitative)
data

In [ ]:
model = OLS(data)
model

In [ ]:
model.melt_coeff()

In [ ]:
model.predict()

In [25]:
data = DataHandler(data_frame=dataframe, target=target, quantitative=quantitative, qualitative=qualitative)
data

In [26]:
from mpydge.wrap.models.regression import KNR

In [27]:
model = KNR(data=data, preprocessor=DeadProcessor, params_space=None)
model

In [28]:
model.fit()

In [29]:
model.predict()

array([   0.,    0.,    0., ..., 9994., 9995., 9995.])

In [ ]:
model.correlation_matrix()

In [ ]:
model.melt_coeff()

In [ ]:
data = DataHandler(data_frame=dataframe, target=target, quantitative=quantitative, qualitative=qualitative)
data

In [ ]:
from mpydge.wrap.models.all import DTR

In [ ]:
model = DTR(data=data, params_space=None)
model

In [ ]:
model.fit()

In [ ]:
model.predict()

In [ ]:
model.correlation_matrix()

In [ ]:
model.melt_coeff()

In [ ]:
data = DataHandler(data_frame=dataframe, target=target, quantitative=quantitative, qualitative=qualitative)
data

In [ ]:
from mpydge.wrap.models.all import ETR

In [ ]:
model = ETR(data=data, params_space=None)
model

In [ ]:
model.fit()

In [ ]:
model.predict()

In [ ]:
model.correlation_matrix()

In [ ]:
model.melt_coeff()

In [ ]:
model.predict()

In [ ]:
data = DataHandler(data_frame=dataframe, target=target, quantitative=quantitative, qualitative=qualitative)
data

In [ ]:
from mpydge.wrap.models.all import RFR

In [ ]:
model = RFR(data=data, params_space=None)
model

In [ ]:
model.fit()

In [ ]:
model.predict()

In [ ]:
model.correlation_matrix()

In [ ]:
model.melt_coeff()

In [ ]:
data = DataHandler(data_frame=dataframe, target=target, quantitative=quantitative, qualitative=qualitative)
data

In [ ]:
from mpydge.wrap.models.all import LBR

In [ ]:
model = LBR(data=data, params_space=None)
model

In [ ]:
model.fit()

In [ ]:
model.predict()

In [ ]:
model.correlation_matrix()

In [ ]:
model.melt_coeff()

In [ ]:
data = DataHandler(data_frame=dataframe, target=target, quantitative=quantitative, qualitative=qualitative)
data

In [ ]:
from mpydge.wrap.models.all import XBR

In [ ]:
model = XBR(data=data, params_space=None)
model

In [ ]:
model.fit()

In [ ]:
model.predict()

In [ ]:
model.correlation_matrix()

In [ ]:
model.melt_coeff()

In [ ]:
data = DataHandler(data_frame=dataframe, target=target, quantitative=quantitative, qualitative=qualitative)
data

In [ ]:
from mpydge.wrap.models.all import SVR

In [ ]:
model = SVR(data=data, params_space=None)
model

In [ ]:
model.fit()

In [ ]:
model.predict()

In [ ]:
model.correlation_matrix()

In [ ]:
model.melt_coeff()

In [15]:
import json

In [16]:
with open('./models_params_mini.json') as f:
    models_params = json.load(f)
model_params = models_params['ETR']
model_params

{'n_estimators': [1000],
 'max_depth': [None, 10, 5, 2],
 'max_features': ['auto'],
 'n_jobs': [-1]}

In [17]:
data = DataHandler(data_frame=dataframe, target=target, quantitative=quantitative, qualitative=qualitative)
data

In [18]:
from mpydge.wrap.models.all import ETR

In [19]:
model = ETR(data=data, params_space=model_params)
model

In [20]:
model.hyper_opt(melt='coeff')

In [21]:
model.data.mask.d0

array([ True,  True,  True, ...,  True,  True,  True])

In [22]:
model.data.mask.d1

array([False,  True,  True])

In [ ]:
model.fit()

In [ ]:
model.data.mask.d0

In [ ]:
model.data.mask.d1

In [ ]:
model.predict()